### ISSUE TITLE
PHP Fatal error:  __autoload() is no longer supported PHP8.2 fix

### ISSUE THREAD

**Issue by furensic** [Jerglekakan/someGelbooruScripts#2]
Hey i just tried to set it up when i ran into the following error:

2024/04/28 23:56:20 [error] 24150#24150: *3360 FastCGI sent in stderr: "PHP message: PHP Fatal error:  __autoload() is no longer supported, use spl_autoload_register() instead in /var/www/x/html/autoload.php on line 2" while reading response header from upstream, client: y, server: x, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "x"

im running php8.2 (latest version on debian12), so i found the fix for it. The fix is to edit autoload.php in the root directory and changing it like the following:

`<?php
	function my_autoloader($class)
	{
		require "classes/$class.class.php";
	}

	spl_autoload_register('my_autoloader');
?>`

since i rarely use github i thought i put this out for the people who have similar issues

**Comment by Jerglekakan** [comment]
Fixed in commit d042edb
