### ISSUE TITLE
Not an issue, comment

### ISSUE THREAD

**Issue by FuzionCD** [Jerglekakan/someGelbooruScripts#3]
@Jerglekakan - So this isn't an issue, more of a comment, but I wanted to make sure you got my message.

I've been trying to decode booru.org (aka Gelbooru 0.1/2) APIs for my own project for a while, and your project laid things out so clearly that I was able to figure out how to parse all the data properly for my project. Thank you for posting & maintaining this repo.

**Comment by Jerglekakan** [comment]
Thanks for the comment. Nice to know someone besides me has gotten some use out of this
